---
collections:
  - name: awx.awx
  - name: ansible.controller
    version: latest
  - name: ansible.posix
  - name: community.general
  - name: community.vmware
  - name: containers.podman
  - name: infra.ah_configuration
  - name: infra.controller_configuration
  - name: infra.ee_utilities
  - name: redhat.rhel_system_roles
  - name: redhat.rhv
  - name: redhat.satellite
  - name: redhat.satellite_operations
  - name: redhat_cop.ah_configuration
  - name: redhat_cop.controller_configuration
  - name: redhat_cop.ee_utilities
  - name: vmware.vmware_rest
