---
- name: post-configure satellite
  hosts: "{{ targeted_host| default('localhost') }}"

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

- name: Include repos.yml 
  ansible.builtin.import_playbook: config/repos.yml
  tags: enable_repos 

- name: Include global_parameters.yml
  ansible.builtin.import_playbook: config/global_parameters.yml
  tags: global_parameters
