---
- name: create image based host 
  hosts: "{{ targeted_host| default('localhost') }}"

  module_defaults:
    redhat.satellite.host:
      username: "{{ satellite_username }}"
      password: "{{ satellite_password }}"
      server_url: "{{ satellite_server_url }}"
      location: "{{ satellite_location }}"
      organization: "{{ satellite_organization }}"
      validate_certs: no

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:
    hg_name_image: []
    compute_profile: []
    image_name: []
    domain_name: "{{ satellite_domain }}"
    num_instances: 1  

  pre_tasks:
    - name: check that required variables are defined
      ansible.builtin.assert:
        that: 
          - domain_name is defined
          - hg_name_image is defined
          - compute_profile is defined
          - image_name is defined
        fail_msg: "domain, hg_name, compute_profile and image_name must be defined"

  tasks:
    - name: create host(s)
      redhat.satellite.host:
        hostgroup: "{{ hg_name_image }}"
        name: "{{ vm_name | default(lookup('community.general.random_pet'), true) ~ (vm_name is defined and num_instances | int > 1 )|ternary(item, '') ~ '.' ~ domain_name }}"
        state: present
        compute_resource: "RHV"
        compute_profile: "{{ compute_profile }}"
        compute_attributes:
          start: "1"
          cpus: "{{ vcpu | default(omit) }}"
          memory_mb: "{{ memory | default(omit) }}"
        provision_method: "image"
        image: "{{ image_name }}"
        build: true
      register: output
      with_sequence: start=1 end="{{ num_instances|default(1) }}"

    - name: set msg output
      set_fact:
        msg: "New VM: {{ output | community.general.json_query('results[*].entity.hosts[*].name') | join('')}}"
      no_log: true

    - name: print new host(s) fqdn
      debug:
        var: msg

    - name: "notify via telegram"
      telegram:
        token: "{{ pinguobot_token }}"
        api_args:
          chat_id: "{{ pinguobot_chatid }}"
          text: "{{ msg }}"
          parse_mode: "markdown"
          disable_web_page_preview: true
          disable_notification: false
      when: notify_via_telegram | bool


# ansible-playbook playbooks/pinguozzo.satellite/create-host-image.yml -e num_instances=2 # it will create 2 instances with random names 
# ansible-playbook playbooks/pinguozzo.satellite/create-host-image.yml -e num_instances=2 -e vm_name=node # it will create 2 instances with hostname: node1, node2
# name: "{{ lookup('ansible.builtin.vars','vm_name' , default=lookup('community.general.random_pet')) + (vm_name is defined and num_instances | int > 1 )|ternary(item, '') + '.' + domain_name, true }}"
# name: "{{ vm_name | default(lookup('community.general.random_pet') + (vm_name is defined and num_instances | int > 1 )|ternary(item, '') + '.' + domain_name, true) }}"
# name: "{{ vm_name | default(lookup('community.general.random_pet') ~ (vm_name is defined and num_instances | int > 1 )|ternary(item, '') ~ '.' ~ domain_name, true) }}"
