---
- name: create vmware host with bootdisk
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: no

  module_defaults:
    redhat.satellite.host:
      username: "{{ satellite_username }}"
      password: "{{ satellite_password }}"
      server_url: "{{ satellite_server_url }}"
      location: "{{ satellite_location }}"
      organization: "{{ satellite_organization }}"
      validate_certs: no

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"


  vars:
    notify_via_telegram: true

  pre_tasks:
    - name: set platform/version specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "RedHat_{{ os_major }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../vars/{{ item }}"
      when: __vars_file is file

  tasks:
    - name: create host(s)
      block:
        - name: create host(s) in vSphere
          redhat.satellite.host:
            username: "{{ satellite_username | default(omit) }}"
            password: "{{ satellite_password | default(omit) }}"
            server_url: "{{ satellite_server_url | default(omit) }}"
            location: "{{ satellite_location }}"  
            organization: "{{ satellite_organization }}"
            validate_certs: "{{ satellite_validate_certs | default(omit) }}"
            name: "{{ vm_name | default(lookup('community.general.random_pet'), true) ~ (vm_name is defined and num_instances | int > 1 )|ternary(item, '') ~ '.' ~ domain_name }}"
              #name: "{{ vm_name | default(lookup('community.general.random_pet'), true) ~ (vm_name is defined and num_instances | int > 1 )|ternary('-' + item, '') ~ '.' ~ domain_name }}"
            state: present
            build: true
            hostgroup: "{{ hg_name }}"
            compute_resource: "VMware"
            compute_profile: "{{ compute_profile|default('2-Medium Generic') }}"
            compute_attributes:
              start: "1"
            ptable: 'Kickstart default'
            provision_method: bootdisk
            operatingsystem: "{{ os }}"
            kickstart_repository: "{{ ks }}"
            subnet: "APPS"
            content_source: "{{ capsule_server }}"
            content_view: "{{ cv }}"
            lifecycle_environment: "LAB"
          register: output
          with_sequence: start=1 end="{{ num_instances|default(1) }}"

        - name: set vms list
          set_fact:
            vms: "{{ output | community.general.json_query('results[*].entity.hosts[*].name') | flatten }} "

        - name: print new host(s) fqdn
          debug:
            msg: "{{ item }}"
          loop:  "{{ vms }}"

        - name: Move vm to corresponding folder
          community.vmware.vmware_guest_move:
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_username }}"
            password: "{{ vcenter_password }}"
            datacenter: DC1
            name: "{{ item }}"
            dest_folder: "/DC1/vm/KNA/RHEL{{ os_major }}"
            validate_certs: false 
          loop: "{{ vms }}"
          delegate_to: localhost

        - name: "notify via telegram"
          telegram:
            token: "{{ pinguobot_token }}"
            api_args:
              chat_id: "{{ pinguobot_chatid }}"
              text: "{{ msg }}"
              parse_mode: "markdown"
              disable_web_page_preview: true
              disable_notification: false
          when: notify_via_telegram | bool
          vars:
            msg: "New RHEL{{ os_major }} VM: {{ output | community.general.json_query('results[*].entity.hosts[*].name') | join('')}} deployed on VMware"
