---
- name: manage content views
  hosts: "{{ targeted_host| default('localhost') }}"

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

- name: Include repos.yml 
  ansible.builtin.import_playbook: repos.yml
  tags: enable_repos  

- name: Include cv_version_create.yml 
  ansible.builtin.import_playbook: cv_version_create.yml
  tags: cv_create  

- name: Include cv_version_publish.yml 
  ansible.builtin.import_playbook: cv_version_publish_promote.yml
  tags: cv_publish

- name: Include cv_version_cleanup.yml 
  ansible.builtin.import_playbook: cv_version_cleanup.yml
  tags: cv_cleanup
