- name: Clean old and unused cvs and ccvs
  hosts: localhost

  vars_files:
    - "{{ playbook_dir }}/../../vaults/infra-vault.yml"

  roles:
    - role: redhat.satellite.content_view_version_cleanup
      vars:
        satellite_content_view_version_cleanup_keep: 0
