- name: Publish cvs
  hosts: localhost

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:
    satellite_composite_content_views:
      - name: ccv-rhel8_soe
      - name: ccv-rhel9_soe
    satellite_content_views:
      - cv-rhel8_soe
      - cv-rhel8_soe_extras
      - cv-rhel9_soe
      - cv-rhel9_soe_extras
      - cv-capsules

    satellite_infra_content_views:
      satellite:
        name: cv-capsules
        lfe: INFRA

    lifecycle_paths:
      - - label: LAB
    lifecycle_environments: "{{ lifecycle_paths|flatten|map(attribute='label')|list }}"

  roles:
    - role: redhat.satellite.content_view_publish

  tasks:
    - name: "Promote composite content views"
      block:
      - name: "Promote composite content views"
        redhat.satellite.content_view_version:
          username: "{{ satellite_username | default(omit) }}"
          password: "{{ satellite_password | default(omit) }}"
          server_url: "{{ satellite_server_url | default(omit) }}"
          validate_certs: "{{ satellite_validate_certs | default(omit) }}"
          content_view: "{{ item.name }}"
          organization: "{{ satellite_organization }}"
          lifecycle_environments: "{{ lifecycle_environments }}"
        loop: "{{ satellite_composite_content_views }}"
      tags: promote

    - name: "Promote infra content views"
      block:
      - name: "Promote infra content views"
        redhat.satellite.content_view_version:
          username: "{{ satellite_username | default(omit) }}"
          password: "{{ satellite_password | default(omit) }}"
          server_url: "{{ satellite_server_url | default(omit) }}"
          validate_certs: "{{ satellite_validate_certs | default(omit) }}"
          content_view: "{{ item.value.name }}"
          organization: "{{ satellite_organization }}"
          lifecycle_environments: "{{ item.value.lfe }}"
        loop: "{{ lookup('ansible.builtin.dict', satellite_infra_content_views, wantlist=True) }}"
      tags: promote,promote_infra
