---
- name: search repos
  hosts: "{{ targeted_host| default('localhost') }}"

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  tasks:
    - name: "Find repository set by name and product."
      redhat.satellite.repository_set_info:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        location: "{{ satellite_location }}"
        organization: "{{ satellite_organization }}"
      register: repos

    - name: debug repos
      debug:
        msg: "{{ item }}"
      with_items: "{{repos.repository_sets.name}}"

    - name: "Set repository sets"
      redhat.satellite.repository_set:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        location: "{{ satellite_location }}"
        organization: "{{ satellite_organization }}"
      with_items: "{{repos.repository_sets}}"
      tags: never  
