- hosts: localhost

  vars_files:
    - "{{ playbook_dir }}/../../vaults/infra-vault.yml"
  
  vars:
    search: label=rhel-8-for-x86_64-appstream-kickstart

  tasks:
    - block:
      - name: "Search for possible repository sets of a product"
        redhat.satellite.resource_info:
          username: "{{ satellite_username }}"
          password: "{{ satellite_password }}"
          server_url: "{{ satellite_server_url }}"
          validate_certs: "{{ satellite_validate_certs }}"
          organization: "{{ satellite_organization }}"
          resource: repository_sets
          search: "{{ search }}"
        register: data

      - name: "Output found repository sets, see the contentUrl section for possible repository substitutions"
        debug:
          var: data
      tags: scan
