---
- name: search repos
  hosts: "{{ targeted_host| default('localhost') }}"

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"
  
  tasks:
    - name: "Find repository set by name and product."
      redhat.satellite.repository_set_info:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_server_url }}"
        validate_certs: "{{ satellite_validate_certs }}"
        organization: "{{ satellite_organization }}"
        search: 'label = "codeready-builder-for-rhel-8-x86_64-rpms"'
        # search: 'label = "ansible-2-for-rhel-9-x86_64-rpms"'
      register: repos

    - name: debug repos
      debug:
        msg: "{{repos}}"

          #  - name: "Set repository sets"
          #    redhat.satellite.repository_set:
          #      username: "{{ satellite_username }}"
          #      password: "{{ satellite_password }}"
          #      server_url: "{{ satellite_server_url }}"
          #      validate_certs: "{{ satellite_validate_certs }}"
          #      organization: "{{ satellite_organization }}"
          #    with_items: "{{repos.repository_sets}}"
          #
          #  - name: "Search for possible repository sets of a product"
          #    redhat.satellite.resource_info:
          #      username: "{{ satellite_username }}"
          #      password: "{{ satellite_password }}"
          #      server_url: "{{ satellite_server_url }}"
          #      validate_certs: "{{ satellite_validate_certs }}"
          #      organization: "{{ satellite_organization }}"
          #      resource: repository_sets
          #      search: "{{ search }}"
          #    register: data
