---
- name: satellite main post-install/configuration
  hosts: "{{ targeted_host| default('localhost') }}"

  tasks:
    - name: load pre-req
      block:
        - name: include env vault
          ansible.builtin.include_vars: "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"
      tags: always
    
- name: Include cv_manage.yml
  ansible.builtin.import_playbook: cv_manage.yml

- name: Include repos.yml
  ansible.builtin.import_playbook: repos.yml
  tags: repos
