---
- name: create host collection and add host(s) to it
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - "{{ playbook_dir }}/../../vaults/infra-vault.yml"

  vars:
    json_query_name: "json.results[*].name"

  tasks:
    - name: load pre-req
      block:
        - name: include infra-vault
          ansible.builtin.include_vars: "{{ playbook_dir }}/../../vaults/infra-vault.yml"

      tags: always
          
    - name: get host list
      uri:
        url: "{{ satellite_server_url }}/api/hosts"
        user: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        method: GET
        return_content: yes
        force_basic_auth: yes
        validate_certs: no
        status_code: [200,201,202]
      no_log: True 
      register: host_list

    - name: set hosts_list
      set_fact: 
        hosts: "{{ host_list| community.general.json_query(json_query_name) }}"
      no_log: True
      loop: 
        - "{{ host_list }}"

    - debug: 
        msg: >-
          {{ hosts }}

    - name: create template    
      ansible.builtin.template:
        src: templates/host-list.j2
        dest: host-list.txt
