---
- name: post-configure satellite
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: no


- name: Include repos.yml 
  ansible.builtin.import_playbook: config/repos.yml
  tags: enable_repos 

- name: Include 3rdparty.yml
  ansible.builtin.import_playbook: config/3rdparty.yml
  tags: 3rdparty

- name: Include global_parameters.yml
  ansible.builtin.import_playbook: config/global_parameters.yml
  tags: global_parameters


