---
- name: manage content views
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: no

  pre_tasks:
    - name: set platform/version/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vars/satellite-{{ hostvars[inventory_hostname].env }}.yml"
      when: __vars_file is file
  
    - name: set login/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vaults/{{ hostvars[inventory_hostname].env }}-vault.yml"
      when: __vars_file is file


- name: Include cv_version_create.yml
  ansible.builtin.import_playbook: cv_version_create.yml
  tags: cv_create

- name: Include cv_version_publish.yml
  ansible.builtin.import_playbook: cv_version_publish_promote.yml
  tags: cv_publish

- name: Include cv_version_cleanup.yml
  ansible.builtin.import_playbook: cv_version_cleanup.yml
  tags: cv_cleanup
