---
- name: create cvs and ccvs
  hosts: "{{ targeted_host| default('localhost') }}"

  vars_files:
    - "{{ playbook_dir }}/../../../vaults/{{ env }}-vault.yml"
    - "{{ playbook_dir }}/../../../vars/satellite-vars.yml"

  roles:
    - role: redhat.satellite.content_views
