---
all:
  vars:
    location: CH
    timezone: Europe\Zurich
  hosts:
    localhost:
      ansible_connection: local
    jumper:
  children:
    CH:
      children: 
      Test:
        hosts:
      LAB:
      Dev:
        vars:
        hosts:
          jumper:
      Prod:
        hosts:
      dc1:
