---
all:
  vars:
    location: CH
    timezone: Europe\Zurich
  hosts:
    localhost:
      ansible_connection: local
    jumper:
  children:
    Test:
      hosts:
    LAB:
    Dev:
      vars:
        lfe: DEV
      hosts:
        jumper:
    Prod:
      hosts:
    dc1:
