---
all:
  vars:
    location: CH
    timezone: Europe\Zurich
  hosts:
    virt-console:
      ansible_host: virt-console.mgmt.zg.pinguozzo.com
      env: mgmt
      infra: yes
    satellite-upstream:
      ansible_host: sat-upstream.mgmt.zg.pinguozzo.com
      env: upstream
      infra: no
    satellite-mgmt:
      ansible_host: satellite.mgmt.zg.pinguozzo.com
      env: mgmt
      infra: yes
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
    jumper:
    terlicium.wg.pinguozzo.com:
      ansible_ssh_host: 10.0.0.10
      ansible_user: rex

  children:
    ddns:
     hosts:
       terlicium.wg.pinguozzo.com
    terlicium:
     hosts:
       terlicium.wg.pinguozzo.com
    INFRA:
      children:
        mgmt:
          hosts:
            satellite-mgmt:
        upstream:
          hosts:
            satellite-upstream:
    CH:
      children:
        Test:
          hosts:
        LAB:
        Dev:
          vars:
          hosts:
            jumper:
        Prod:
          hosts:
        dc1:
...