---
all:
  vars:
    location: CH
    timezone: Europe\Zurich
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
    jumper:
  children:
    CH:
      children: 
        Test:
          hosts:
        LAB:
        Dev:
          vars:
          hosts:
            jumper:
        Prod:
          hosts:
        dc1:
    IT:
    SG:
      children:
        DevCloud:
