---
all:
  vars:
    location: CH
    timezone: Europe\Zurich
  hosts:
    bombino.mgmt.zg.pinguozzo.com:
    verdeca.mgmt.zg.pinguozzo.com:
    aleatico.mgmt.zg.pinguozzo.com:
    sm01.mgmt.zg.pinguozzo.com:
      infra: yes
    sm02.mgmt.zg.pinguozzo.com:
      infra: yes
    sm03.mgmt.zg.pinguozzo.com:
      infra: yes
    virt-console:
      ansible_host: virt-console.mgmt.zg.pinguozzo.com
      env: mgmt
      infra: yes
    satellite-upstream:
      ansible_host: sat-upstream.mgmt.zg.pinguozzo.com
      env: upstream
      infra: no
    satellite-mgmt:
      ansible_host: satellite.mgmt.zg.pinguozzo.com
      env: mgmt
      infra: yes
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    INFRA:
      children:
        ceph:
          vars:
            ansible_become: true
            ansible_user: rex
            ansible_python_interpreter: auto
          hosts:
            bombino.mgmt.zg.pinguozzo.com:
            verdeca.mgmt.zg.pinguozzo.com:
            aleatico.mgmt.zg.pinguozzo.com:
        rhvh:
          vars:
            ansible_user: rex
            ansible_python_interpreter: auto
          hosts:
            sm01.mgmt.zg.pinguozzo.com:
            sm02.mgmt.zg.pinguozzo.com:
            sm03.mgmt.zg.pinguozzo.com:
        mgmt:
          vars:
            ansible_connection: local
          hosts:
            satellite-mgmt:
        upstream:
          vars:
            ansible_connection: local
          hosts:
            satellite-upstream:
...
