---
- ovirt_vm_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ vm_name }}"
    follow: 'diskattachments.disk'
  register: vm_info

- debug: var=vm_info

- debug:
    msg: "{{ vm_info.ovirt_vms[0].disk_attachments[0].disk.id }}"
