---
- ovirt_vm_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ vm_name }}"
    fetch_nested: true
    nested_attributes: disks  
  register: vm_info

- name: show info about the host 
  debug: 
    msg: >
      - Hostname is: {{ vm_info.ovirt_vms[0].fqdn }}
      - Disk id: {{ vm_info.ovirt_vms[0].disk_attachments[0].id }}

- ovirt_disk:
    auth: "{{ ovirt_auth }}"
    id: "{{ vm_info.ovirt_vms[0].disk_attachments[0].id }}"
    storage_domain: Ceph_iSCSI
    name: "{{ vm_info.ovirt_vms[0].fqdn }}"
    vm_name: "{{ vm_info.ovirt_vms[0].fqdn }}"

