---
- name: oVirt shutdown environment
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: true

  collections:
    - redhat.rhv

  vars_files:
    - "{{ playbook_dir }}/../../vaults/engine_vars.yml"

  vars:

  roles:
    - role: shutdown_env
