---
- hosts: "{{ targeted_host| default('localhost') }}"

  vars_files:
    - "{{ playbook_dir }}/../../../vaults/{{ env }}-vault.yml"
    - "{{ playbook_dir }}/../../../vars/satellite-vars.yml"

  vars:

  pre_tasks:
    - name: Create Content Crendentials
      redhat.satellite.content_credential:
        username: "{{ satellite_username | default(omit) }}"
        password: "{{ satellite_password | default(omit) }}"
        server_url: "{{ satellite_server_url | default(omit) }}"
        validate_certs: "{{ satellite_validate_certs | default(omit) }}"
        organization: "{{ satellite_organization }}"
        name: "{{ item.name }}"
        content_type: "{{ item.content_type }}"
        content: "{{ item.content }}"
      loop: "{{ satellite_content_credentials }}"

  tasks:

    - name: 3rd Party products
      redhat.satellite.product:
        username: "{{ satellite_username | default(omit) }}"
        password: "{{ satellite_password | default(omit) }}"
        server_url: "{{ satellite_server_url | default(omit) }}"
        organization: "{{ satellite_organization }}"
        validate_certs: "{{ satellite_validate_certs | default(omit) }}"
        name: "{{ item.name }}"
          #sync_plan: "{{ item.sync_plan | default(omit) }}"
        state: present
      loop: "{{ additional_products }}"
      tags: 3rd_party_products

    - name: "3rd Party repos"
      redhat.satellite.repository:
        username: "{{ satellite_username | default(omit) }}"
        password: "{{ satellite_password | default(omit) }}"
        server_url: "{{ satellite_server_url | default(omit) }}"
        organization: "{{ satellite_organization }}"
        validate_certs: "{{ satellite_validate_certs | default(omit) }}"
        name: "{{ item.name }}"
        content_type: "yum"
        url: "{{ item.url|default(omit) }}"
        http_proxy_policy: "{{ item.http_proxy_policy|default(omit) }}"
        http_proxy: "{{ item.http_proxy|default(omit) }}"
        gpg_key: "{{ item.gpg_key|default(omit) }}"
        product: "{{ item.product }}"
        mirror_on_sync: "{{ item.mirror_on_sync|default(false) }}"
        os_versions: "{{ item.os_version|default(omit) }}"
        unprotected: "{{ item.unprotected|default(omit) }}"
        download_policy: "{{ item.download_policy|default(omit) }}"
      loop: "{{ additional_repos }}"
      tags: 3rd_party_repos

        #    - name: enable sync for products
        #      redhat.satellite.repository_sync:
        #        username: "{{ satellite_username | default(omit) }}"
        #        password: "{{ satellite_password | default(omit) }}"
        #        server_url: "{{ satellite_server_url | default(omit) }}"
        #        validate_certs: "{{ satellite_validate_certs | default(omit) }}"
        #        organization: "{{ satellite_organization }}"
        #        repository: "{{ item.name }}"
        #        product: "{{ item.product }}"
        #      loop: "{{ additional_repos }}"
        #      when: sync_repos
