---
- name: "add lifecycle environment(s)"
  redhat.satellite.lifecycle_environment:
    server_url: "{{ satellite_server_url }}"
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    organization: "{{ satellite_organization }}"
    validate_certs: false
    name: "{{ item.name | default(item.label) }}"
    label: "{{ item.label }}"
    prior: "{{ item.prior | default((lce_idx > 0) | ternary(lcp_item[lce_idx-1]['label'], 'Library')) }}"
    description: "{{ item.desc | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ lcp_item }}"
  loop_control:
    index_var: lce_idx
