---
vm_data:
  #name: '{{ vm_name }}'
  interfaces:
    - adapter:
        ipv4:
          type: STATIC
          gateways:
            - '{{ gateway_ip }}'
          ip_address: '{{ vm_ip }}'
          prefix: 24

infra:
  domain: "{{ network_domain }}"
  time_zone: 'Europe\Zurich'
  dns:
    dns_servers: 
      - '{{ dns_server |default(omit) }}'
    dns_suffix_list:
      - '{{ network_domain | default(omit) }}'

swap_disk_size: "10.00 GB"
