---
satellite_compute_profiles:
  - name: "VMware Medium RHEL9 ESX NET_apps"
    compute_attributes:
      - compute_resource: "{{ lookup('ansible.builtin.vars', 'satellite_compute_resource', default='')}}"
        vm_attrs:
          cluster: "{{ lookup('ansible.builtin.vars', 'vcenter_cluster', default='')}}"
            #path: /Datacenter/vm/
          path: /Datacenters/DC1/vm/
          scsi_controllers:
          - type: ParaVirtualSCSIController  
          memoryHotAddEnabled: true
          cpuHotAddEnabled: true
          cpus: 2
          corespersocket: 1
          memory_mb: 4096
          add_cdrom: "1"
          guest_id: "rhel9_64Guest"
          volumes_attributes:
            0:
              datastore: "{{ lookup('ansible.builtin.vars', 'vcenter_datastore', default='')}}"
              size_gb: 30
          interfaces_attributes:
            0:
              type: "VirtualVmxnet3"
              network: "VLAN 5"

  - name: "VMware Medium RHEL8 ESX NET_apps"
    compute_attributes:
      - compute_resource: "{{ lookup('ansible.builtin.vars', 'satellite_compute_resource', default='')}}"
        vm_attrs:
          cluster: "{{ lookup('ansible.builtin.vars', 'vcenter_cluster', default='')}}"
            #path: /Datacenter/vm/
          path: /Datacenters/DC1/vm/
          scsi_controllers:
          - type: ParaVirtualSCSIController  
          memoryHotAddEnabled: true
          cpuHotAddEnabled: true
          cpus: 2
          corespersocket: 1
          memory_mb: 4096
          add_cdrom: "1"
          guest_id: "rhel8_64Guest"
          volumes_attributes:
            0:
              datastore: "{{ lookup('ansible.builtin.vars', 'vcenter_datastore', default='')}}"
              size_gb: 30
          interfaces_attributes:
            0:
              type: "VirtualVmxnet3"
              network: "VLAN 5"

