---
- name: create activation keys
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: no  

  vars_files:
    - "{{ playbook_dir }}/../../../vaults/{{ env }}-vault.yml"
    - "{{ playbook_dir }}/../../../vars/satellite-vars.yml"

  roles:
    - role: redhat.satellite.activation_keys
