---
- name: Include init.yml
  ansible.builtin.import_playbook: init.yml
  tags: init,always

- name: Include disconnected.yml
  ansible.builtin.import_playbook: disconnected.yml
  tags: disconnected
  when: set_disconnected | bool

- name: Include storage.yml
  ansible.builtin.import_playbook: storage.yml
  tags: lvm
  when: set_lvm | bool

- name: Include satellite-installer.yml
  ansible.builtin.import_playbook: satellite-installer.yml
  tags: installer
  when: set_installer | bool

- name: Include manifest.yml
  ansible.builtin.import_playbook: manifest.yml
  tags: manifest
  when: set_manifest | bool

- name: Include location.yml
  ansible.builtin.import_playbook: location.yml
  tags: locations
  when: set_locations | bool

- name: Include global_parameters.yml
  ansible.builtin.import_playbook: global_parameters.yml
  tags: global
  when: set_global | bool

- name: Include repos.yml
  ansible.builtin.import_playbook: repos.yml
  tags: repos
  when: set_repos | bool

- name: Include repo_sync.yml
  ansible.builtin.import_playbook: repo_sync.yml
  tags: sync
  when: set_sync | bool

- name: Include 3rdparty.yml
  ansible.builtin.import_playbook: 3rdparty.yml
  tags: 3rdparty
  when: set_3rdparty | bool

- name: Include sync-plan.yml
  ansible.builtin.import_playbook: sync-plan.yml
  tags: sync_plan
  when: set_sync_plan | bool

- name: Include environment.yml
  ansible.builtin.import_playbook: environments.yml
  tags: environments
  when: set_environments | bool

- name: Include cv_manage.yml
  ansible.builtin.import_playbook: "{{ playbook_dir }}/../content/cv_manage.yml"
  tags: cv
  when: set_cv | bool

- name: Include activation_keys.yml
  ansible.builtin.import_playbook: "{{ playbook_dir }}/../config/activation_keys.yml"
  tags: ak
  when: set_ak | bool

...
