---
- name: Satellite ansible installer
  hosts: "{{ targeted_host| default('localhost') }}"
  become: false

  pre_tasks:
    - name: Set platform/version/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vars/satellite-{{ hostvars[inventory_hostname].env }}.yml"
      when: __vars_file is file
    - name: Set login/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vaults/{{ hostvars[inventory_hostname].env }}-vault.yml"
      when: __vars_file is file


  tasks:
    - name: Loop through the life cycle paths
      include_tasks:
        file: lfe.yml
      loop: "{{ lifecycle_paths }}"
      loop_control:
        loop_var: lcp_item
