---
- name: Set Lifecycles Environments
  hosts: "{{ targeted_host| default('localhost') }}"
  become: false
  gather_facts: false

  tasks:
    - name: Loop through the life cycle paths
      include_tasks:
        file: lfe.yml
      loop: "{{ lifecycle_paths }}"
      loop_control:
        loop_var: lcp_item
