---
- name: Run init
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: false

  vars:

  tasks:
    - name: Set platform/version/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vars/{{ hostvars[inventory_hostname].env }}.yml"
      when: __vars_file is file

    - name: Set login/env specific variables
      include_vars: "{{ __vault_file }}"
      loop:
        - "{{ hostvars[inventory_hostname].env }}-vault.yml"
      vars:
        __vault_file: "{{ playbook_dir }}/../../../vaults/{{ hostvars[inventory_hostname].env }}-vault.yml"
      when: __vault_file is file

#     - name: run if how in groups
#       debug: msg="host in group"
#       when: inventory_hostname in lookup('inventory_hostnames', 'mgmt:upstream')
