---
- name: run init 
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: no

  tasks:
    - name: set platform/version/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vars/satellite-{{ hostvars[inventory_hostname].env }}.yml"
      when: __vars_file is file
  
    - name: set login/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vaults/{{ hostvars[inventory_hostname].env }}-vault.yml"
      when: __vars_file is file

    - name: run if how in groups
      debug: msg="host in group"
      when: inventory_hostname in lookup('inventory_hostnames', 'mgmt:upstream')
