---
- name: "Add locations"
  redhat.satellite.location:
     username: "{{ satellite_username | default(omit) }}"
     password: "{{ satellite_password | default(omit) }}"
     server_url: "{{ satellite_server_url | default(omit) }}"
     validate_certs: "{{ satellite_validate_certs | default(omit) }}"
     name: "{{ item.name | default(item.parent) }}"
     parent: "{{ item.parent | default((loc_idx > 0) | ternary(loc_item[loc_idx - 1]['parent'], '')) }}"
     organizations: "{{ item.organizations | default(omit) }}"
     parameters: "{{ item.parameters | default(omit) }}"
     ignore_types: "{{ item.ignore_types | default(omit) }}"
  loop: "{{ loc_item }}"
  loop_control:
     index_var: loc_idx
