---
- name: Configure locations
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: false

  tasks:
    - name: Loop through the satellite locations
      include_tasks:
        file: loc.yml
      loop: "{{ satellite_locations }}"
      loop_control:
        loop_var: loc_item
