---
- name: configure sync_plan
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: no

  pre_tasks:
    - name: set platform/version/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vars/satellite-{{ hostvars[inventory_hostname].env }}.yml"
      when: __vars_file is file
  
    - name: set login/env specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "satellite-{{ hostvars[inventory_hostname].env }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../../vaults/{{ hostvars[inventory_hostname].env }}-vault.yml"
      when: __vars_file is file

  roles:
    - role: redhat.satellite.sync_plans
      vars:
        satellite_sync_plans:
          - name: RHEL SOE Daily
            interval: daily
            sync_date: 2020-11-07 00:00:00 UTC
            products: "{{ satellite_products | map(attribute='name') | list }}"

          - name: Weekly SOE
            interval: weekly
            sync_date: 2020-11-07 00:00:00 UTC
            products: "{{ additional_products | map(attribute='name') | list | default(omit)}}"
