---
- name: associate vm to compute resource
  hosts: to_register
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:
    json_query_name: "json.results[*].name"

  tasks:
    - name: associate to cr 
      block:
      - name: get host compute resource list
        uri:
          url: "{{ satellite_server_url }}/api/compute_resources/"
          user: "{{ satellite_username }}"
          password: "{{ satellite_password }}"
          method: GET
          return_content: yes
          force_basic_auth: yes
          validate_certs: no
          status_code: [200,201,202]
        no_log: True 
        register: cr_result
        tags: cr_search

      - name: set_fact cr_list
        set_fact:
          cr_list: "{{ cr_result | community.general.json_query(json_query_name) | join(', ') }}"
        no_log: True
        tags: cr_search

      - name: get cr names and id
        set_fact:
          cr_vmware_id: "{{ item.id }}"
          #cr_vmware_id: "{{ cr|default({}) | combine ( {item.name : item.id } ) }}"
        with_items: "{{ cr_result| community.general.json_query('json.results[*]')}}" 
        when: 
          - not item.provider | regex_search('^VMware*')
        no_log: True
        tags: cr_search

      - name: show cr, id{{':'}}
        debug: var=cr_vmware_id
        tags: cr_search

      - name: get VMware compute resource vms list
        uri:
          url: "{{ satellite_server_url }}/api/compute_resources/{{ cr_vmware_id }}/available_virtual_machines"
          user: "{{ satellite_username }}"
          password: "{{ satellite_password }}"
          method: GET
          return_content: yes
          force_basic_auth: yes
          validate_certs: no
          status_code: [200,201,202]
        no_log: True
        register: cr_vms_result
        tags: cr_search

      - name: get vms id(s)
        set_fact:
          vms: "{{ vms|default({}) | combine ( {item.name : item.id } ) }}"
        loop: "{{ cr_vms_result| community.general.json_query('json[*]')}}"
        #when: not item.provider | regex_search('^VMware*')
        when:
          #- item.name is not match('^VMware')
          - item.name == inventory_hostname
        no_log: True
        tags: cr_search

      - name: show vms 
        debug: var=vms
        tags: cr_search

      - name: assign vms to compute resource 
        uri:
          url: "{{ satellite_server_url }}/api/compute_resources/{{cr_vmware_id }}/associate/{{ item.id }}"
          user: "{{ satellite_username }}"
          password: "{{ satellite_password }}"
          method: PUT
          return_content: yes
          force_basic_auth: yes
          validate_certs: no
          status_code: [200,201,422]
          body_format: json
        loop: "{{ cr_vms_result| community.general.json_query('json[*]')}}"
        when:
          #- item.name is not match('^VMware')
          - item.name == inventory_hostname
        no_log: True
        tags: cr_search

      - name: get_vm id
        uri:
          url: "{{ satellite_server_url }}/api/hosts?search={{ inventory_hostname }}"
          user: "{{ satellite_username }}"
          password: "{{ satellite_password }}"
          method: GET
          return_content: yes
          force_basic_auth: yes
          validate_certs: no
          status_code: [200,201,202]
        no_log: True
        register: get_vm
        tags: get_vm

      - name: set_fact vm_id {{ inventory_hostname }}
        set_fact:
          vm_id: "{{ item.id }}"
        loop:
          - "{{ get_vm | community.general.json_query(json_query) | join(', ') }}"
        vars:
          json_query: "json.results[*]"
        no_log: True

      - name: show vm_id for {{ inventory_hostname }}
        debug:
          msg: "{{ vm_id }}"

      - name: assign vm to hostgroup
        uri:
          url: "{{ satellite_server_url }}/api/hosts/{{ vm_id }}/"
          user: "{{ satellite_username }}"
          password: "{{ satellite_password }}"
          method: PUT
          return_content: yes
          force_basic_auth: yes
          validate_certs: no
          status_code: [200,201,422]
          body_format: json
          body: '{"host":{ "hostgroup_id": 62 }}'
        no_log: True

      delegate_to: localhost

    - name: ensure cloud-init is disabled
      ansible.builtin.file:
        path: /etc/cloud/cloud-init.disabled
        state: touch
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      when: ip_mode == "static"

    - name: shutdown vm
      community.general.shutdown:
      become: True  
      tags: never
