---
- name: configure swap 
  hosts: to_register
  become: true

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"
    - "{{ playbook_dir }}/../../vars/parameters.yml"

  vars:

  pre_tasks:
    - name: pre-check and device identification
      block:
        # - name: check if /etc/lvm/devices/system.devices file exists
        #   ansible.builtin.stat:
        #     path: /etc/lvm/devices/system.devices 
        #   register: st

        - name: create initial /etc/lvm/devices/system.devices file if not exists
          ansible.builtin.command: 
            cmd: vgimportdevices --all
            creates: /etc/lvm/devices/system.devices 
          when:
            #    - st.stat.exists == false
            - >-
              ansible_facts['distribution_major_version'] | int >= 9

        - name: identify disks that are {{ swap_size }} GB for swap_vg
          set_fact:
            swap_vg_disks: "{{ ansible_devices | dict2items | selectattr('key', 'match', '^sd.*') | rejectattr('key', 'match', '^sda$') | selectattr('value.size', 'match', '^' ~ swap_disk_size ) | map(attribute='key') | list }}"

        - name: show value of {{ swap_disk_size }} swap_vg_disks
          ansible.builtin.debug:
            var: swap_vg_disks

  roles:
    - name: redhat.rhel_system_roles.storage
      vars:
        storage_pools:
        - name: swapvg
          disks: "{{ swap_vg_disks }}"
          volumes:
            - name: swap
              size: 40%
              fs_type: swap
              state: present
