---
- name: configure swap 
  hosts: to_register
  become: true

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:
    storage_pools:
    - name: swapvg
      disks:
        - /dev/sdb
      volumes:
        - name: swap
          size: 80%
          fs_type: swap
          state: present

  pre_tasks:

    - name: check if /etc/lvm/devices/system.devices file exists
      ansible.builtin.stat:
        path: /etc/lvm/devices/system.devices 
      register: st

    - name: create initial /etc/lvm/devices/system.devices file if not exists
      ansible.builtin.command: vgimportdevices --all
      when: st.stat.exists == false

  roles:
    - name: redhat.rhel_system_roles.storage
