---
- name: add targeted_host to in-memory inventory
  hosts: localhost
  become: no
  gather_facts: false
  tags: always

  tasks:
    - name: add targeted_host to group
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        groups: init
        ansible_ssh_host: '{{ vm_ip }}'
      loop: 
        - "{{ targeted_host }}"

    - name: show hosts
      debug: var=groups['init']

    - name: wait for vm to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 900
      loop: "{{ groups['init'] }}"

- name: create missing users
  hosts: init
  gather_facts: true

  pre_tasks:
    - name: include rex-users vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../vars/rex-user.yml"

  roles: 
    - "{{ playbook_dir }}/../../roles/pinguozzo.create-users"

- name: install RHEL/Fedora web console (cockpit)
  hosts: init
  roles:
    - redhat.rhel_system_roles.cockpit
  vars:
    cockpit_packages: default
  tags: cockpit

- name: configure firewall for web console
  hosts: all
  roles:
    - redhat.rhel_system_roles.firewall
  vars:
    firewall:
      service: cockpit
  tags: cockpit
