---
- name: play1 create in-memory inventory
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: yes

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:
  pre_tasks:

  tasks:
    - name: check connectivity
      ping:

    - name: add aap controller to group
      ansible.builtin.add_host:
        hostname: "{{ controller_hostname }}"
        groups: aap
 
    - name: show controller host
      debug: var=groups['aap']

    - name: wait for vm to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 900
      delegate_to: "{{ item }}"
      loop: "{{ groups['aap'] }}"

- name: play2 get images and push to execution nodes
  hosts: aap
  gather_facts: yes

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:
  pre_tasks:

  tasks:
    - name: get images list
      shell: podman images -n --format "table {{ '{{' }} .Repository {{ '}}' ' ' '{{' }} .Tag {{ '}}' }}"|tr -s ' '|sed "s/ /:/g"
      become: true
      become_user: awx
      register: images

    - name: show images to sync
      debug:
        msg="{{ images.stdout_lines }}"

    - name: push images to execution nodes
      command: "podman image scp {{ item.0.name }} {{ item.1.name }}::"
      args:
        chdir: $HOME
      loop: "{{ ee_name | subelements('con_name') }}"
      become: true
      become_user: awx


# example data structure ee_name:
#
# ee_name:
#   - name:  localhost/ee-supported-rhel8:latest
#     target:
#       - name: aap-xnode2.example.com
#     con_name:
#       - name: XNODE2
# setup podman system connection: https://www.redhat.com/sysadmin/podman-transfer-container-images-without-registry
