---
- name: add builder host to in-memory inventory
  hosts: localhost
  gather_facts: yes

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  tasks:
    - name: add targeted_host to to_register group
      ansible.builtin.add_host:
        hostname: "{{ builder_host }}"
        groups: builder 
 
    - name: show host to register
      debug: var=groups['builder']

    - name: wait for vm to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 900
      delegate_to: "{{ item }}"
      loop: "{{ groups['builder'] }}"

- name: create custom EE
  hosts: "{{ builder | default('localhost') }}"
  gather_facts: false
  collections:
    - infra.ee_utilities
  vars:
    ee_builder_dir_clean: true
    ah_host: "{{ vaulted_ah_host }}"
    ah_token: "{{ vaulted_ah_token }}"
    ee_registry_dest: "{{ vaulted_ah_host }}"
    ee_base_registry_username: "{{ vaulted_ee_base_registry_username }}"
    ee_base_registry_password: "{{ vaulted_ee_base_registry_password }}"
    ee_base_image: "{{ vaulted_ee_base_image }}"
    ee_builder_image: "{{ vaulted_ee_builder_image }}"

    ee_list:
      - name: custom-build
        # base_image
        bindep:
          - libxml2-devel [platform:rpm]
          - libcurl-devel [platform:rpm]
          - python3-devel [platform:rpm]
          - python3-requests [platform:rpm]
        python:
          - awxkit  # For import and export modules
          - petname
          - xmltodict
          - jmespath
          - requests
        # - Pyvmomi (duplicated - included in community.vmware)
        collections:
          - name: ansible.controller
          - name: awx.awx
          - name: community.general
          - name: community.vmware
          - name: containers.podman
          - name: infra.controller_configuration
          - name: infra.ah_configuration
          - name: infra.ee_utilities
          - name: redhat_cop.ah_configuration
          - name: redhat_cop.controller_configuration
          - name: redhat_cop.ee_utilities
          - name: redhat.satellite
          - name: redhat.satellite_operations
          - name: redhat.rhel_system_roles
          - name: vmware.vmware_rest

  roles:
    - infra.ee_utilities.ee_builder
...
