---
- name: update host list in job_template host-delete
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - infra.controller

  vars_files:
    - "{{ playbook_dir }}/../../vaults/infra-vault.yml"

  vars:
    json_query_name: "json.results[*].name"

  pre_tasks:
    - name: include vars from controller_configs directory
      include_vars:
        dir: ../../configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

    - name: get host list
      uri:
        url: "{{ satellite_server_url }}/api/hosts"
        user: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        method: GET
        return_content: yes
        force_basic_auth: yes
        validate_certs: no
        status_code: [200,201,202]
      no_log: True 
      register: host_list

    - name: set hosts_list
      set_fact: 
        hosts: "{{ host_list| community.general.json_query(json_query_name) }}"
      no_log: True
      loop: 
        - "{{ host_list }}"

    - name: create a new token using controller username/password
      ansible.controller.token:
        description: 'Creating token to test controller jobs'
        scope: "write"
        state: present
        validate_certs: false
        controller_host: "{{ controller_hostname }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
      when: not controller_token

  roles:
    - {role: infra.controller_configuration.job_templates, when: controller_templates is defined}
...
