---
- name: check
  hosts: all
  become: no
  gather_facts: true

  tasks:
    - name: include rex-users vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../vars/rex-user.yml"
      
  roles: 
    - "{{ playbook_dir }}/../../roles/pinguozzo.create-users"
