---
- name: create in-memory inventory
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: yes 

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:

  pre_tasks:

  tasks:
    - name: check connectivity
      ping:

    - name: add targeted_host to group
      ansible.builtin.add_host:
        hostname: "{{ controller_hostname }}"
        groups: aap
 
    - name: show controller host
      debug: var=groups['aap']

    - name: wait for vm to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 900
      delegate_to: "{{ item }}"
      loop: "{{ groups['aap'] }}"


- name: get images and push to EEs
  hosts: aap
  gather_facts: yes 

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:

  pre_tasks:

  tasks:

    - name: get images list
      shell: podman images -n --format "table {{ '{{' }} .Repository {{ '}}' ' ' '{{' }} .Tag {{ '}}' }}"|tr -s ' '|sed "s/ /:/g"
      become: true
      become_user: awx
      register: images

    - name: show images to sync
      debug:
        msg="{{ images.stdout_lines }}"

    - name: push images to execution nodes
      debug:
        msg: "podman image scp {{ item }} {{ HOSTNAME }}::"
      loop: "{{ images.stdout_lines }}"
      become: true
      become_user: awx
      register: images
