---
- name: check ip update
  hosts: "{{ targeted_host| default('all') }}"
  gather_facts: no

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:

  pre_tasks:

  tasks:
    - name: check connectivity
      ping:
