---
- name: check ip update
  hosts: "{{ targeted_host| default('localhost') }}"
  gather_facts: yes 

  vars_files:

  vars:

  pre_tasks:

  tasks:
    - name: check connectivity
      ping:

    - name: print hosts information
      ansible.builtin.debug:
        msg: System {{ inventory_hostname }} has hostname {{  ansible_hostname }}

