---
- name: add host to in-memory inventory
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  tasks:
    - name: add targeted_host to post_install group
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        groups: post_install
      loop: "{{ targeted_host }}"

    - name: show host to register
      debug: var=groups['post_install']

    - name: wait for vm to become reachable
      ansible.builtin.ping:
      delegate_to: "{{ item }}"
      loop: "{{ groups['post_install'] }}"

- name: post-install playbook
  hosts: post_install
  serial: true
  gather_facts: true
  become: true  

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  pre_tasks:
    - name: set platform/version specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "{{ ansible_facts['os_family'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - >-
          {{ ansible_facts['distribution'] ~ '_' ~
          ansible_facts['distribution_major_version'] }}.yml
      vars:
        __vars_file: "{{ playbook_dir }}/../../vars/{{ item }}"
      when: __vars_file is file

  tasks:
    - name: post-install for rhel6
      block:
        - name: ensure not required packages are absent
          ansible.builtin.yum:
            name: katello-host-tools
            state: absent

        - name: ensure required packages are present
          ansible.builtin.yum:
            disable_excludes: all
            name: "{{ install_packages }}"
            exclude: "{{ exclude_packages }}"
            state: present

        - name: ensure excluded packages are saved
          ansible.builtin.lineinfile:
            path: /etc/yum.conf
            line: exclude="{{ item.split() | join(' ')  }}"
            backrefs: yes
          loop: "{{ excluded_packages }}"

      when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "6")

    - name: post-install for rhel7
      block:
        - name: ensure not required packages are absent
          ansible.builtin.yum:
            name: katello-host-tools
            state: absent

        - name: ensure required packages are present
          ansible.builtin.yum:
            name: "{{ install_packages }}"
            exclude: "{{ exclude_packages }}"
            state: present
      when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7")

    - name: post-install for rhel8
      block:
        - name: ensure not required packages are absent
          ansible.builtin.yum:
            name: katello-host-tools
            state: absent

        - name: ensure required packages are present
          ansible.builtin.yum:
            name: "{{ install_packages }}"
            exclude: "{{ exclude_packages }}"
            state: present
      when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8")

    - name: post-install for rhel9
      block:
        - name: ensure not required packages are absent
          ansible.builtin.yum:
            name: katello-host-tools
            state: absent

        - name: ensure required packages are present
          ansible.builtin.yum:
            name: "{{ install_packages }}"
            exclude: "{{ exclude_packages }}"
            state: present
      when: (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
