---
- name: add host to in-memory inventory
  hosts: localhost
  gather_facts: true

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  tasks:
    - name: add targeted_host to to_register group
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        groups: post_install
      loop: 
        - "{{ targeted_host }}"

    - name: show host to register
      debug: var=groups['post_install']

    - name: wait for vm to become reachable
      ansible.builtin.ping:
      delegate_to: "{{ item }}"
      loop: "{{ groups['post_install'] }}"

- name: post-install playbook
  hosts: "{{ post_install| default('all') }}"
  serial: true
  gather_facts: no

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  pre_tasks:
    - name: set platform/version specific variables
      include_vars: "{{ __vars_file }}"
      loop:
        - "RedHat_{{ os_major }}.yml"
      vars:
        __vars_file: "{{ playbook_dir }}/../../vars/{{ item }}"
      when: __vars_file is file

  tasks:
    - name: post-install for rhel6
      block:
        - name: ensure not required packages are absent
          ansible.builtin.yum:
            name: katello-host-tools
            state: absent

        - name: ensure required packages are present
          ansible.builtin.yum:
            name: "{{ install_packages }}"
            state: present
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_.major_version <= 6

