---
- name: Playbook to create custom EE
- name: Create EE 
  hosts: "{{ targeted_host | default('localhost') }}"
  gather_facts: false

  vars_files:
    - "{{ playbook_dir }}/../../vaults/{{ env }}-vault.yml"

  vars:
    ee_builder_dir_clean: true
    ah_host: "{{ vaulted_ah_host }}"
    ah_token: "{{ vaulted_ah_token }}"
    ee_registry_dest: "{{ vaulted_ee_registry_dest }}"
    ee_base_registry_username: "{{ vaulted_ee_base_registry_username }}"
    ee_base_registry_password: "{{ vaulted_ee_base_registry_password }}"
    ee_base_image: "{{ vaulted_ee_base_image }}"
    ee_builder_image: "{{ vaulted_ee_builder_image }}"

    ee_list:
      - name: custom-build
        dependencies:
          system:
            - libxml2-devel [platform:rpm]
            - libcurl-devel [platform:rpm]
            - python3-devel [platform:rpm]
            - python3-requests [platform:rpm]
            - openssl [platform:rpm]
          python:
            - awxkit  # For import and export modules
            - petname
            - xmltodict
            - jmespath
            - requests
            - lxml
            - dnspython
          galaxy:
            collections:
              - name: ansible.controller
              - name: ansible.posix
              - name: awx.awx
              - name: community.general
              - name: community.vmware
              - name: containers.podman
              - name: infra.controller_configuration
              - name: infra.ah_configuration
              - name: infra.ee_utilities
              - name: redhat_cop.ah_configuration
              - name: redhat_cop.controller_configuration
              - name: redhat_cop.ee_utilities
              - name: redhat.satellite
              - name: redhat.satellite_operations

  roles:
    - infra.ee_utilities.ee_builder
...
